### ISSUE TITLE
Test DE performance on BBOB 2012 testbed

### ISSUE THREAD

**Issue by ChinChangYang** [rzdx/FHF#10]
Test DE performance on BBOB 2012 testbed.

Reference:
1. Hansen, Nikolaus, et al. "Real-parameter black-box optimization benchmarking 2012: Experimental setup." (2012).
2. COmparing Continuous Optimisers: COCO [Online] http://coco.gforge.inria.fr/doku.php?id=bbob-2012

**Comment by ChinChangYang** [comment]
Please paste (or attach) the results here.

**Comment by rzdx** [comment]
![image](https://f.cloud.github.com/assets/5179299/1313321/aa9d72d4-3254-11e3-8733-498c9d3adde3.png)
